spring:
  datasource:
    url: jdbc:mariadb://yachtclubdb.c5g8su8m6qt4.eu-central-1.rds.amazonaws.com:3308/yachtclub
    password: 
    username: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        connection:
          characterEncoding: utf8mb4
          useUnicode: true
          CharSet: utf8mb4
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: yachtclubpolsl@gmail.com
    password: tblo ohpr rpiq zmdy
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF-8
        smtp:
          writetimeout: 100000
          connectiontimeout: 100000
          timeout: 100000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: http://localhost:8080