spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/yachtclub
    password: root
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always